### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#36]
With this code:

```
define i = analogPinIn[0]

when start {
   variable a = 0
   display "hello"
   a = get i
   }
```

I get a null pointer exception:

```
Exception in thread "main" java.lang.NullPointerException
	at parser.Parser.parseStatement(Parser.java:372)
	at parser.Parser.parseBlockStatement(Parser.java:504)
	at parser.Parser.parseWhenStatement(Parser.java:86)
	at parser.Parser.parseProgram(Parser.java:33)
	at parser.Parser.parse(Parser.java:20)
	at Interpreter.main(Interpreter.java:16)
```

**Comment by ooee123** [comment]
Quick patch of misplacing the equality token as the assignment token.
