### ISSUE TITLE
java.lang.Exception: Stack trace

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#44]
first line of buzz input file is:

```
define test = serv[3]
```

The error is
```
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1364)
	at parser.Parser.error(Parser.java:1324)
	at parser.Parser.expected(Parser.java:1319)
	at parser.Parser.parseMachinery(Parser.java:249)
	at parser.Parser.parseDeclarations(Parser.java:185)
	at parser.Parser.parseProgram(Parser.java:27)
	at parser.Parser.parse(Parser.java:20)
	at Interpreter.main(Interpreter.java:16)
```

**Comment by ooee123** [comment]
I think it should work for servo[3]

Typo?

**Comment by jsseng** [comment]
I was intentionally testing with the typo.
